### ISSUE TITLE
Potential bug in calculating `lags_for_fourier_time_features_from_frequency` function

### ISSUE THREAD

**Issue by hashbangCoder** [zalandoresearch/pytorch-ts#42]
Hello,

I was trying to understand the code execution and stumbled across a potential bug.
The `lags_for_fourier_time_features_from_frequency()`  returns an incorrect result when you pass a minute level `freq` arg.

Example : `lags_for_fourier_time_features_from_frequency(freq='10min') == [1]`  when it should return `[1, 4, 12, 24, 48]` 

For other frequencies it works as expected -
- `lags_for_fourier_time_features_from_frequency(freq='1D') == [1, 7, 14]`
- `lags_for_fourier_time_features_from_frequency(freq='10M') == [1, 12]`

Could you please explain why `max(lags)` is added to `self.history_length` to increase context len in [here](https://github.com/zalandoresearch/pytorch-ts/blob/86c89c4f58dcb8f15a37773efd7455257a9be4d2/pts/model/tempflow/tempflow_estimator.py#L106) ?

**Comment by kashif** [comment]
@hashbangCoder so yes the issue with the `lags_for_fourier_time_features_from_frequency` for `min` freq. should be fixed now...


regarding why `max(lags)` is added to the context is because we need to paste in the values from some time back and so want to make sure that the window is big enough given the lag features indicies... hope that answers it?
