### ISSUE TITLE
how to extract the predicted cross-covariance matrix from estimators?

### ISSUE THREAD

**Issue by sgdantas** [zalandoresearch/pytorch-ts#69]
Hi, first of all, great work.

I was wondering how to recover the information shown in Fig. 5 in the tempflow paper https://arxiv.org/abs/2002.06103

Thanks!

**Comment by kashif** [comment]
Right so that figure was made by first recalling that the ground truth is a matrix of dim: `[T,D]` and the predictions are `S=100` or so sample predictions so a tensor of shape `[T,S,D]`. If I remember correctly we first calculate the mean of each time step of the prediction to obtain `[T,D]` matrix. Finally, we can calculate the cross-covariance of the ground truth and this prediction matrix and the last figure is the absolute difference of these cross covariances. 

Hope that helps?

**Comment by sgdantas** [comment]
awesome, thanks!
Closing the issue
